name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Install SVN build dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
              libssl-dev libsqlite3-dev libapr1-dev libaprutil1-dev
          else
            # macOS - install dependencies via homebrew
            brew install autoconf automake libtool pkg-config openssl sqlite apr apr-util
          fi

      - name: Install asdf
        uses: asdf-vm/actions/setup@v4
        
      - name: Test plugin installation and functionality
        env:
          ASDF_SVN_SKIP_DEPS_CHECK: "true"
        run: |
          # Add plugin from local directory
          asdf plugin add svn "${{ github.workspace }}"
          
          # Test list-all command
          echo "Testing asdf list-all svn..."
          available_versions=$(asdf list-all svn | head -5)
          echo "Available versions:"
          echo "$available_versions"
          
          # Get latest version for testing
          latest_version=$(asdf list-all svn | tail -1)
          echo "Latest version: $latest_version"
          
          # Install the latest version
          echo "Installing SVN version: $latest_version"
          asdf install svn "$latest_version"
          
          # Set it as global
          asdf global svn "$latest_version"
          
          # Test that SVN works
          echo "Testing svn --version:"
          svn --version
