name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Install SVN build dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
              libssl-dev libsqlite3-dev libapr1-dev libaprutil1-dev
          else
            # macOS - install dependencies via homebrew
            brew install autoconf automake libtool pkg-config openssl sqlite apr apr-util
            
            # Debug: Check what homebrew installed and where
            echo "=== Homebrew APR Debug Info ==="
            echo "APR install location:"
            find $(brew --prefix) -name "*apr*config*" 2>/dev/null || echo "No apr config files found"
            echo "APR packages:"
            brew list | grep apr || echo "No APR packages found"
            echo "APR-UTIL packages:"
            brew list | grep apr || echo "No APR-UTIL packages found"
            echo "Homebrew prefix: $(brew --prefix)"
            echo "==============================="
          fi

      - name: Install asdf
        uses: asdf-vm/actions/setup@v4
        
      - name: Test plugin installation and functionality
        env:
          ASDF_SVN_SKIP_DEPS_CHECK: "true"
        run: |
          # Add plugin from local directory
          asdf plugin add svn "${{ github.workspace }}"
          
          # Test list-all command
          echo "Testing asdf list-all svn..."
          asdf list-all svn
          
          # Use latest available version for testing
          test_version=$(asdf list-all svn | tail -1)
          echo "Testing with SVN version: $test_version"
          
          # Install and test the version
          echo "Installing SVN version: $test_version"
          asdf install svn "$test_version"
          
          # Set it as global
          asdf global svn "$test_version"
          
          # Test that SVN works
          echo "Testing svn --version:"
          svn --version
