name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install basic dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf automake libtool pkg-config
          else
            # macOS - dependencies should be available or installable via system tools
            brew install autoconf automake libtool pkg-config || true
          fi

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: svn --version
        env:
          # Skip complex dependency checking in CI for now
          ASDF_SVN_SKIP_DEPS_CHECK: "true"
