name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Install SVN build dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
              libssl-dev libsqlite3-dev libapr1-dev libaprutil1-dev
          else
            # macOS - install dependencies via homebrew
            brew install autoconf automake libtool pkg-config openssl sqlite apr apr-util
          fi

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: svn --version
        env:
          # Skip complex dependency checking in CI for now
          ASDF_SVN_SKIP_DEPS_CHECK: "true"
